name: flimenv-0.3.0
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - matplotlib>3.4
  - numpy=1.18
  - pandas=1.1
  - pip=20.3
  - python=3.7
  - pytorch=1.7.0
  - torchinfo=1.6.3
  - scikit-learn
  - seaborn
  - xlsxwriter
  - networkx=2.5.1
  - wxpython=4.0.4
  - pip:
    - pypubsub
    - importlib-resources
