[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]

# version = "0.0.1"  # Remove any existing version parameter.
dynamic = ["version"]

[tool.setuptools_scm]
write_to = "flim/_version.py"