name: docs
channels:
  - pytorch
  - defaults
dependencies:
  - matplotlib=3
  - numpy=1.18
  - pandas=1.1
  - pip=20.3
  - python=3.7
  - pytorch=1.7.0
  - scikit-learn
  - seaborn
  - xlsxwriter
  - wxpython
  - Sphinx==3.5.4
  - sphinx-rtd-theme==0.5.2
  - pip:
    - pypubsub
    - myst-parser==0.13.7
